### ISSUE TITLE
Can't connect to a server

### ISSUE THREAD

**Issue by markx** [Teddy-Zhu/electronic-mud#1]
After I put domain and port, it showed this:
<img width="532" alt="screen shot 2017-05-10 at 8 51 57 pm" src="https://cloud.githubusercontent.com/assets/1816385/25927258/bd0411ce-35c2-11e7-91b1-559b80c4b2b1.png">

Looks like [here](https://github.com/Teddy-Zhu/electronic-mud/blob/master/backend/main.js#L141),  the arguments for `name, host, port` passed in are incorrect, which in my case are `undefined 'tab3' 'bat.org'`.

**Comment by Teddy-Zhu** [comment]
sorry for the lately reply, i fix it in 536a8f4afc1d992d6c9b367ebaa69458408c443f
